# Generated by Django 4.2.4 on 2023-08-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements81',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements81',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisements81',
            name='bu',
            field=models.BooleanField(default=False, help_text='Отметьте, использовался ли товар до продажи.', verbose_name='б\\у'),
        ),
    ]
