# Generated by Django 4.2.4 on 2023-08-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_advertisements81_image_advertisements81_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements81',
            table='advertisements',
        ),
    ]
